// <auto-generated />
using System;
using Food.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Food.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Food.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "icecream",
                            Name = "Snacks",
                            Url = "snacks"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "lunch_dining",
                            Name = "Dinners",
                            Url = "dinners"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "brunch_dining",
                            Name = "Suppers",
                            Url = "suppers"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "breakfast_dining",
                            Name = "Breakfasts",
                            Url = "breakfasts"
                        });
                });

            modelBuilder.Entity("Food.Shared.CustomerOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            DateCreated = new DateTime(2022, 1, 30, 14, 31, 52, 822, DateTimeKind.Local).AddTicks(6243),
                            OrderId = 1,
                            PaymentMode = "Cart"
                        });
                });

            modelBuilder.Entity("Food.Shared.Edition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Editions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Small"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Big"
                        });
                });

            modelBuilder.Entity("Food.Shared.OrderDetail", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Food.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryID = 4,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pancakes with maple syrup and fruit",
                            Image = "https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Pancakes"
                        },
                        new
                        {
                            Id = 2,
                            CategoryID = 4,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sandwiches with eggs and avocado",
                            Image = "https://images.pexels.com/photos/566566/pexels-photo-566566.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Sandwiches"
                        },
                        new
                        {
                            Id = 3,
                            CategoryID = 4,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bagel with cheese, bacon, egg, tomato and salad",
                            Image = "https://images.pexels.com/photos/139746/pexels-photo-139746.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Bagel"
                        },
                        new
                        {
                            Id = 4,
                            CategoryID = 4,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Breakfast set including coffee, bread, slices of salmon and cheese, yoghurt, wafers and fruit",
                            Image = "https://images.pexels.com/photos/86753/pexels-photo-86753.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Breakfast set"
                        },
                        new
                        {
                            Id = 5,
                            CategoryID = 4,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Oatmeal with baked pear",
                            Image = "https://images.pexels.com/photos/4488082/pexels-photo-4488082.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Oatmeal"
                        },
                        new
                        {
                            Id = 6,
                            CategoryID = 4,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Croissant",
                            Image = "https://images.pexels.com/photos/3892469/pexels-photo-3892469.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Croissant"
                        },
                        new
                        {
                            Id = 7,
                            CategoryID = 3,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Baked salmon with vegetable pie",
                            Image = "https://images.pexels.com/photos/5439041/pexels-photo-5439041.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Baked salmon"
                        },
                        new
                        {
                            Id = 8,
                            CategoryID = 3,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Salad with cottage cheese, pumpkin and seeds",
                            Image = "https://images.pexels.com/photos/10281067/pexels-photo-10281067.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Cottage cheese salad"
                        },
                        new
                        {
                            Id = 9,
                            CategoryID = 3,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Feta cheese salad with strawberries, pumpkin and olives",
                            Image = "https://images.pexels.com/photos/992824/pexels-photo-992824.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Feta cheese salad"
                        },
                        new
                        {
                            Id = 10,
                            CategoryID = 3,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stuffed peppers with hot sauce",
                            Image = "https://images.pexels.com/photos/5339083/pexels-photo-5339083.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Stuffed peppers"
                        },
                        new
                        {
                            Id = 11,
                            CategoryID = 3,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Baked fish with asparagus, mild sauce and oranges",
                            Image = "https://images.pexels.com/photos/8112939/pexels-photo-8112939.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Baked fish"
                        },
                        new
                        {
                            Id = 12,
                            CategoryID = 3,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Original italian risotto",
                            Image = "https://images.pexels.com/photos/9058939/pexels-photo-9058939.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Risotto"
                        },
                        new
                        {
                            Id = 13,
                            CategoryID = 2,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Beef burger with fries",
                            Image = "https://images.pexels.com/photos/1199957/pexels-photo-1199957.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Beef burger"
                        },
                        new
                        {
                            Id = 14,
                            CategoryID = 2,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chicken kebab",
                            Image = "https://images.pexels.com/photos/2955819/pexels-photo-2955819.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Kebab"
                        },
                        new
                        {
                            Id = 15,
                            CategoryID = 2,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Original Thai cousine",
                            Image = "https://images.pexels.com/photos/6646364/pexels-photo-6646364.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Pad Thai"
                        },
                        new
                        {
                            Id = 16,
                            CategoryID = 2,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Georgian Chinkali with broth and vegetables",
                            Image = "https://images.pexels.com/photos/5409015/pexels-photo-5409015.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Chinkali"
                        },
                        new
                        {
                            Id = 17,
                            CategoryID = 2,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Italian pizza with pepperoni and gorgonzola cheese",
                            Image = "https://images.pexels.com/photos/825661/pexels-photo-825661.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Pizza"
                        },
                        new
                        {
                            Id = 18,
                            CategoryID = 2,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pasta with chicken and cheese sauce",
                            Image = "https://images.pexels.com/photos/1438672/pexels-photo-1438672.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Pasta"
                        },
                        new
                        {
                            Id = 19,
                            CategoryID = 1,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "French fries with sauce",
                            Image = "https://images.pexels.com/photos/1893556/pexels-photo-1893556.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "French fries"
                        },
                        new
                        {
                            Id = 20,
                            CategoryID = 1,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Donut",
                            Image = "https://images.pexels.com/photos/867452/pexels-photo-867452.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Donut"
                        },
                        new
                        {
                            Id = 21,
                            CategoryID = 1,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cheese board including gorgonzola, parmesan, chevre and camembert",
                            Image = "https://images.pexels.com/photos/6660056/pexels-photo-6660056.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Cheese board"
                        },
                        new
                        {
                            Id = 22,
                            CategoryID = 1,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nachos with salsa",
                            Image = "https://images.pexels.com/photos/9974358/pexels-photo-9974358.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Nachos"
                        },
                        new
                        {
                            Id = 23,
                            CategoryID = 1,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chicken wings with barbecue sauce",
                            Image = "https://images.pexels.com/photos/2338407/pexels-photo-2338407.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Chicken wings"
                        },
                        new
                        {
                            Id = 24,
                            CategoryID = 1,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Original Indian bread",
                            Image = "https://images.pexels.com/photos/1117862/pexels-photo-1117862.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Plain naan"
                        });
                });

            modelBuilder.Entity("Food.Shared.ProductVariant", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("EditionId")
                        .HasColumnType("int");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId", "EditionId");

                    b.HasIndex("EditionId");

                    b.ToTable("ProductVariant");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            EditionId = 1,
                            OriginalPrice = 9.99m,
                            Price = 6.99m
                        },
                        new
                        {
                            ProductId = 1,
                            EditionId = 2,
                            OriginalPrice = 0m,
                            Price = 12.99m
                        },
                        new
                        {
                            ProductId = 1,
                            EditionId = 3,
                            OriginalPrice = 19.99m,
                            Price = 15.99m
                        },
                        new
                        {
                            ProductId = 2,
                            EditionId = 1,
                            OriginalPrice = 5.99m,
                            Price = 3.99m
                        },
                        new
                        {
                            ProductId = 2,
                            EditionId = 2,
                            OriginalPrice = 8.99m,
                            Price = 7.99m
                        },
                        new
                        {
                            ProductId = 2,
                            EditionId = 3,
                            OriginalPrice = 11.99m,
                            Price = 10.99m
                        },
                        new
                        {
                            ProductId = 3,
                            EditionId = 1,
                            OriginalPrice = 0m,
                            Price = 5.99m
                        },
                        new
                        {
                            ProductId = 3,
                            EditionId = 2,
                            OriginalPrice = 0m,
                            Price = 6.99m
                        },
                        new
                        {
                            ProductId = 3,
                            EditionId = 3,
                            OriginalPrice = 0m,
                            Price = 7.99m
                        },
                        new
                        {
                            ProductId = 4,
                            EditionId = 1,
                            OriginalPrice = 14.00m,
                            Price = 8.99m
                        },
                        new
                        {
                            ProductId = 4,
                            EditionId = 2,
                            OriginalPrice = 18.00m,
                            Price = 14.66m
                        },
                        new
                        {
                            ProductId = 4,
                            EditionId = 3,
                            OriginalPrice = 24.00m,
                            Price = 20.66m
                        },
                        new
                        {
                            ProductId = 5,
                            EditionId = 1,
                            OriginalPrice = 8m,
                            Price = 6.99m
                        },
                        new
                        {
                            ProductId = 5,
                            EditionId = 2,
                            OriginalPrice = 11m,
                            Price = 9.99m
                        },
                        new
                        {
                            ProductId = 5,
                            EditionId = 3,
                            OriginalPrice = 15m,
                            Price = 12.99m
                        },
                        new
                        {
                            ProductId = 6,
                            EditionId = 1,
                            OriginalPrice = 5m,
                            Price = 3.74m
                        },
                        new
                        {
                            ProductId = 6,
                            EditionId = 2,
                            OriginalPrice = 8m,
                            Price = 5.74m
                        },
                        new
                        {
                            ProductId = 6,
                            EditionId = 3,
                            OriginalPrice = 10m,
                            Price = 7.74m
                        },
                        new
                        {
                            ProductId = 7,
                            EditionId = 1,
                            OriginalPrice = 12.99m,
                            Price = 10.99m
                        },
                        new
                        {
                            ProductId = 7,
                            EditionId = 2,
                            OriginalPrice = 0m,
                            Price = 14.99m
                        },
                        new
                        {
                            ProductId = 7,
                            EditionId = 3,
                            OriginalPrice = 18.99m,
                            Price = 16.99m
                        },
                        new
                        {
                            ProductId = 8,
                            EditionId = 1,
                            OriginalPrice = 7.99m,
                            Price = 7.99m
                        },
                        new
                        {
                            ProductId = 8,
                            EditionId = 2,
                            OriginalPrice = 9.99m,
                            Price = 8.99m
                        },
                        new
                        {
                            ProductId = 8,
                            EditionId = 3,
                            OriginalPrice = 12.99m,
                            Price = 9.99m
                        },
                        new
                        {
                            ProductId = 9,
                            EditionId = 1,
                            OriginalPrice = 0m,
                            Price = 7.99m
                        },
                        new
                        {
                            ProductId = 9,
                            EditionId = 2,
                            OriginalPrice = 0m,
                            Price = 8.99m
                        },
                        new
                        {
                            ProductId = 9,
                            EditionId = 3,
                            OriginalPrice = 0m,
                            Price = 9.99m
                        },
                        new
                        {
                            ProductId = 10,
                            EditionId = 1,
                            OriginalPrice = 0m,
                            Price = 6.99m
                        },
                        new
                        {
                            ProductId = 10,
                            EditionId = 2,
                            OriginalPrice = 0m,
                            Price = 7.99m
                        },
                        new
                        {
                            ProductId = 10,
                            EditionId = 3,
                            OriginalPrice = 0m,
                            Price = 8.99m
                        },
                        new
                        {
                            ProductId = 11,
                            EditionId = 1,
                            OriginalPrice = 0m,
                            Price = 10.99m
                        },
                        new
                        {
                            ProductId = 11,
                            EditionId = 2,
                            OriginalPrice = 0m,
                            Price = 14.99m
                        },
                        new
                        {
                            ProductId = 11,
                            EditionId = 3,
                            OriginalPrice = 0m,
                            Price = 16.99m
                        },
                        new
                        {
                            ProductId = 12,
                            EditionId = 1,
                            OriginalPrice = 0m,
                            Price = 7.99m
                        },
                        new
                        {
                            ProductId = 12,
                            EditionId = 2,
                            OriginalPrice = 0m,
                            Price = 9.99m
                        },
                        new
                        {
                            ProductId = 12,
                            EditionId = 3,
                            OriginalPrice = 0m,
                            Price = 12.99m
                        },
                        new
                        {
                            ProductId = 13,
                            EditionId = 1,
                            OriginalPrice = 0m,
                            Price = 8.99m
                        },
                        new
                        {
                            ProductId = 13,
                            EditionId = 2,
                            OriginalPrice = 0m,
                            Price = 12.99m
                        },
                        new
                        {
                            ProductId = 13,
                            EditionId = 3,
                            OriginalPrice = 0m,
                            Price = 16.99m
                        },
                        new
                        {
                            ProductId = 14,
                            EditionId = 1,
                            OriginalPrice = 0m,
                            Price = 7.99m
                        },
                        new
                        {
                            ProductId = 14,
                            EditionId = 2,
                            OriginalPrice = 0m,
                            Price = 11.99m
                        },
                        new
                        {
                            ProductId = 14,
                            EditionId = 3,
                            OriginalPrice = 0m,
                            Price = 15.99m
                        },
                        new
                        {
                            ProductId = 15,
                            EditionId = 1,
                            OriginalPrice = 0m,
                            Price = 11.99m
                        },
                        new
                        {
                            ProductId = 15,
                            EditionId = 2,
                            OriginalPrice = 0m,
                            Price = 13.99m
                        },
                        new
                        {
                            ProductId = 15,
                            EditionId = 3,
                            OriginalPrice = 0m,
                            Price = 16.99m
                        },
                        new
                        {
                            ProductId = 16,
                            EditionId = 1,
                            OriginalPrice = 0m,
                            Price = 7.99m
                        },
                        new
                        {
                            ProductId = 16,
                            EditionId = 2,
                            OriginalPrice = 0m,
                            Price = 9.99m
                        },
                        new
                        {
                            ProductId = 16,
                            EditionId = 3,
                            OriginalPrice = 0m,
                            Price = 12.99m
                        },
                        new
                        {
                            ProductId = 17,
                            EditionId = 1,
                            OriginalPrice = 0m,
                            Price = 9.99m
                        },
                        new
                        {
                            ProductId = 17,
                            EditionId = 2,
                            OriginalPrice = 0m,
                            Price = 12.99m
                        },
                        new
                        {
                            ProductId = 17,
                            EditionId = 3,
                            OriginalPrice = 0m,
                            Price = 15.99m
                        },
                        new
                        {
                            ProductId = 18,
                            EditionId = 1,
                            OriginalPrice = 0m,
                            Price = 7.99m
                        },
                        new
                        {
                            ProductId = 18,
                            EditionId = 2,
                            OriginalPrice = 0m,
                            Price = 8.99m
                        },
                        new
                        {
                            ProductId = 18,
                            EditionId = 3,
                            OriginalPrice = 0m,
                            Price = 12.99m
                        },
                        new
                        {
                            ProductId = 19,
                            EditionId = 1,
                            OriginalPrice = 0m,
                            Price = 4.99m
                        },
                        new
                        {
                            ProductId = 19,
                            EditionId = 2,
                            OriginalPrice = 0m,
                            Price = 5.99m
                        },
                        new
                        {
                            ProductId = 19,
                            EditionId = 3,
                            OriginalPrice = 0m,
                            Price = 6.99m
                        },
                        new
                        {
                            ProductId = 20,
                            EditionId = 1,
                            OriginalPrice = 0m,
                            Price = 2.99m
                        },
                        new
                        {
                            ProductId = 20,
                            EditionId = 2,
                            OriginalPrice = 0m,
                            Price = 3.99m
                        },
                        new
                        {
                            ProductId = 20,
                            EditionId = 3,
                            OriginalPrice = 0m,
                            Price = 4.99m
                        },
                        new
                        {
                            ProductId = 21,
                            EditionId = 1,
                            OriginalPrice = 0m,
                            Price = 10.99m
                        },
                        new
                        {
                            ProductId = 21,
                            EditionId = 2,
                            OriginalPrice = 0m,
                            Price = 14.99m
                        },
                        new
                        {
                            ProductId = 21,
                            EditionId = 3,
                            OriginalPrice = 0m,
                            Price = 18.99m
                        },
                        new
                        {
                            ProductId = 22,
                            EditionId = 1,
                            OriginalPrice = 0m,
                            Price = 4.99m
                        },
                        new
                        {
                            ProductId = 22,
                            EditionId = 2,
                            OriginalPrice = 0m,
                            Price = 6.99m
                        },
                        new
                        {
                            ProductId = 22,
                            EditionId = 3,
                            OriginalPrice = 0m,
                            Price = 7.99m
                        },
                        new
                        {
                            ProductId = 23,
                            EditionId = 1,
                            OriginalPrice = 0m,
                            Price = 6.99m
                        },
                        new
                        {
                            ProductId = 23,
                            EditionId = 2,
                            OriginalPrice = 0m,
                            Price = 7.99m
                        },
                        new
                        {
                            ProductId = 23,
                            EditionId = 3,
                            OriginalPrice = 0m,
                            Price = 9.99m
                        },
                        new
                        {
                            ProductId = 24,
                            EditionId = 1,
                            OriginalPrice = 0m,
                            Price = 3.99m
                        },
                        new
                        {
                            ProductId = 24,
                            EditionId = 2,
                            OriginalPrice = 0m,
                            Price = 4.99m
                        },
                        new
                        {
                            ProductId = 24,
                            EditionId = 3,
                            OriginalPrice = 0m,
                            Price = 6.99m
                        });
                });

            modelBuilder.Entity("Food.Shared.UserRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Taszkient",
                            Email = "admin@admin.pl",
                            Name = "admin",
                            Password = "admin123",
                            Phone = "123456789",
                            PostCode = "21-123",
                            Street = "kunickiego 12"
                        });
                });

            modelBuilder.Entity("Food.Shared.CustomerOrder", b =>
                {
                    b.HasOne("Food.Shared.UserRegister", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Food.Shared.OrderDetail", b =>
                {
                    b.HasOne("Food.Shared.CustomerOrder", "Order")
                        .WithMany("Products")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Food.Shared.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Food.Shared.Product", b =>
                {
                    b.HasOne("Food.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Food.Shared.ProductVariant", b =>
                {
                    b.HasOne("Food.Shared.Edition", "Edition")
                        .WithMany()
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Food.Shared.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Edition");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Food.Shared.CustomerOrder", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Food.Shared.Product", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
